### ISSUE TITLE
`title` and `society` of `cvEntry` are swapped compared to the thumbnails

### ISSUE THREAD

**Issue by Lelio-Brun** [mintyfrankie/brilliant-CV#62]
Hello, it seems that the current version of the package formats `title` and `society` inversely compared to the thumbnails. 
That is, `society` appears now as the main heading of the entry. I do not know if this was intended or if this is a regression.

**Comment by mintyfrankie** [comment]
Hi,

```toml
[layout.entry]
        # Decide if you want to put your company in bold or your position in bold
        display_entry_society_first = true
```

Feel free to try this setting in `metadata.toml` :)
